:------------------------- WARNING ! ----------------------
:         This file is GENERATED by Instant Rails.
:
: If you need to make changes to this file, you should edit
: the source template file instead. The source template is
: F:\InstantRails\conf_files\use_ruby.cmd
:-----------------------------------------------------------
CD F:\InstantRails
PATH F:\InstantRails\ruby\bin;F:\InstantRails\mysql\bin;%PATH%
cd rails_apps
cd track

ruby script\console


