:------------------------- WARNING ! ----------------------
:         This file is GENERATED by Instant Rails.
:
: If you need to make changes to this file, you should edit
: the source template file instead. The source template is
: E:\InstantRails\conf_files\use_ruby.cmd
:-----------------------------------------------------------
CD E:\InstantRails
PATH E:\InstantRails\ruby\bin;E:\InstantRails\mysql\bin;%PATH%
cd rails_apps
cd track
ruby script\server -e production -p 80


